language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-21.1.1

# Disable travis email notifications until builds work properly
notifications:
  email: false

before_script:
  # Create and start emulator if you want to run tests
  - echo no | android create avd --force -n test -t $ANDROID_TARGET -c 1024M --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &
  - chmod +x travis-build.sh
  - chmod +x android/source/gradlew

script: ./travis-build.sh
